version: '3.1'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./initial_database/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh