spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
    platform: postgres
    initialize: false
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  database:
    driverClassName: org.postgresql.Driver
  liquibase:
    default-schema: liquibase
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: application
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 360000

rules:
  payment:
    interest: #percentage
      1.to.3.days: 2
      4.to.5.days: 3
      6.days.or.more: 5
    fine.per.day: #percentage
      1.to.3.days: 0.1
      4.to.5.days: 0.2
      6.days.or.more: 0.3